#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : neofetch
Version  : 6.0.0
Release  : 7
URL      : https://github.com/dylanaraps/neofetch/archive/6.0.0.tar.gz
Source0  : https://github.com/dylanaraps/neofetch/archive/6.0.0.tar.gz
Summary  : A CLI system information tool written in BASH that supports displaying images.
Group    : Development/Tools
License  : MIT
Requires: neofetch-bin = %{version}-%{release}
Requires: neofetch-license = %{version}-%{release}
Requires: neofetch-man = %{version}-%{release}
Patch1: clearlinux.patch

%description
<h3 align="center"><img src="https://i.imgur.com/ZQI2EYz.png" alt="logo" height="100px"></h3>
<p align="center">A command-line system information tool written in bash 3.2+</p>

%package bin
Summary: bin components for the neofetch package.
Group: Binaries
Requires: neofetch-license = %{version}-%{release}
Requires: neofetch-man = %{version}-%{release}

%description bin
bin components for the neofetch package.


%package license
Summary: license components for the neofetch package.
Group: Default

%description license
license components for the neofetch package.


%package man
Summary: man components for the neofetch package.
Group: Default

%description man
man components for the neofetch package.


%prep
%setup -q -n neofetch-6.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547043710
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1547043710
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/neofetch
cp LICENSE.md %{buildroot}/usr/share/package-licenses/neofetch/LICENSE.md
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/neofetch

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/neofetch/LICENSE.md

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/neofetch.1
